image: golang:1.7

pipelines:
  default:
    - step:
        script:
          - # extract current version to the output path
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          # install dependencies
          - apt-get update
          - apt-get --yes install libnlopt-dev gfortran libopenblas-dev
          - apt-get --yes install libgsl0-dev # for plotting
          - CGO_LDFLAGS="-lopenblas" go get github.com/gonum/blas/cgo
          # now godon
          - go get bitbucket.org/Davydov/godon/godon
          - cd "${PACKAGE_PATH}"
          - go test -v -short ./...
          - #benchmarks are currently disabled
          - #go test ./... -run=NONE -bench=.
