image: golang:1.7

pipelines:
  default:
    - step:
        script:
          - # extract current version to the output path
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - # nlopt
          - apt-get update
          - apt-get --yes install libnlopt-dev
          # go-lbfgsb
          - apt-get --yes install gfortran
          - go get -d github.com/afbarnard/go-lbfgsb
          - cd $GOPATH/src/github.com/afbarnard/go-lbfgsb
          - make
          - go get github.com/afbarnard/go-lbfgsb
          # gonum and other libs
          - go get -d github.com/gonum/blas
          - go get -d github.com/gonum/matrix
          - go get -d github.com/gonum/floats
          - go get github.com/skelterjohn/go.matrix
          - go get github.com/op/go-logging
          - # gonum plot for some binaries
          - apt-get --yes install libgsl0-dev
          - go get github.com/biogo/graphics/bezier
          - go get github.com/gonum/plot
          - # now godon
          - cd "${PACKAGE_PATH}"
          - #GODEBUG=cgocheck=0 is needed until go-lbfgsb gets fixed
          - GODEBUG=cgocheck=0 go test -v -short ./...
          - go install bitbucket.org/Davydov/godon/godon
          - #benchmarks are currently disabled
          - #go test ./... -run=NONE -bench=.
