package bio

// GeneticCodes is a map holding genetic codes.
// This file was generated using gcode program from NCBI genetic codes file.
var GeneticCodes = map[int]*GeneticCode{
	1: newGeneticCode(1,
		"Standard",
		"SGC0",
		"FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"---M---------------M---------------M----------------------------"),
	2: newGeneticCode(2,
		"Vertebrate Mitochondrial",
		"SGC1",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSS**VVVVAAAADDEEGGGG",
		"--------------------------------MMMM---------------M------------"),
	3: newGeneticCode(3,
		"Yeast Mitochondrial",
		"SGC2",
		"FFLLSSSSYY**CCWWTTTTPPPPHHQQRRRRIIMMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"----------------------------------MM----------------------------"),
	4: newGeneticCode(4,
		"Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma",
		"SGC3",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"--MM---------------M------------MMMM---------------M------------"),
	5: newGeneticCode(5,
		"Invertebrate Mitochondrial",
		"SGC4",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG",
		"---M----------------------------MMMM---------------M------------"),
	6: newGeneticCode(6,
		"Ciliate Nuclear; Dasycladacean Nuclear; Hexamita Nuclear",
		"SGC5",
		"FFLLSSSSYYQQCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	9: newGeneticCode(9,
		"Echinoderm Mitochondrial; Flatworm Mitochondrial",
		"SGC8",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
		"-----------------------------------M---------------M------------"),
	10: newGeneticCode(10,
		"Euplotid Nuclear",
		"SGC9",
		"FFLLSSSSYY**CCCWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	11: newGeneticCode(11,
		"Bacterial, Archaeal and Plant Plastid",
		"",
		"FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"---M---------------M------------MMMM---------------M------------"),
	12: newGeneticCode(12,
		"Alternative Yeast Nuclear",
		"",
		"FFLLSSSSYY**CC*WLLLSPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-------------------M---------------M----------------------------"),
	13: newGeneticCode(13,
		"Ascidian Mitochondrial",
		"",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSGGVVVVAAAADDEEGGGG",
		"---M------------------------------MM---------------M------------"),
	14: newGeneticCode(14,
		"Alternative Flatworm Mitochondrial",
		"",
		"FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	15: newGeneticCode(15,
		"Blepharisma Macronuclear",
		"",
		"FFLLSSSSYY*QCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	16: newGeneticCode(16,
		"Chlorophycean Mitochondrial",
		"",
		"FFLLSSSSYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	21: newGeneticCode(21,
		"Trematode Mitochondrial",
		"",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
		"-----------------------------------M---------------M------------"),
	22: newGeneticCode(22,
		"Scenedesmus obliquus Mitochondrial",
		"",
		"FFLLSS*SYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-----------------------------------M----------------------------"),
	23: newGeneticCode(23,
		"Thraustochytrium Mitochondrial",
		"",
		"FF*LSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"--------------------------------M--M---------------M------------"),
	24: newGeneticCode(24,
		"Pterobranchia Mitochondrial",
		"",
		"FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG",
		"---M---------------M---------------M---------------M------------"),
	25: newGeneticCode(25,
		"Candidate Division SR1 and Gracilibacteria",
		"",
		"FFLLSSSSYY**CCGWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"---M-------------------------------M---------------M------------"),
	26: newGeneticCode(26,
		"Pachysolen tannophilus Nuclear",
		"",
		"FFLLSSSSYY**CC*WLLLAPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
		"-------------------M---------------M----------------------------"),
}
